### ISSUE TITLE
Fix CI status badge in README

### ISSUE THREAD

**Issue by j4mie** [dabapps/django-readers#61]
This seems to just be showing the status of whatever the most recent build happened to be, rather than the status of the `main` branch. Need to investigate. Thanks for the report @simkimsia

**Comment by j4mie** [comment]
Thanks! Your "quick fix" is perfect. I'm not a big fan of pre-commit personally.

**Comment by j4mie** [comment]
Fixed in #63

**Comment by j4mie** [comment]
Ah this still doesn't work 😆 CI doesn't run on `main` so it just says "no status". What we want is the status of whatever the last thing that was merged into main is.. which probably isn't possible?

I'm not actually sure what value this badge really adds... maybe we should just remove it.

**Comment by j4mie** [comment]
I think a good way to do this would be to add

```
on:
  push:
    branches:
      - main
```

To the GitHub Actions config so that the tests _do_ run against `main` after a merge. This means the badge represents "do the tests pass against current `main`, which I think is what we want.

**Comment by simkimsia** [comment]
sounds good. wanna try?

**Comment by j4mie** [comment]
It works! 🙂 

<img width="330" alt="image" src="https://user-images.githubusercontent.com/6988/179182994-b40b8b39-a8e9-4194-96aa-02bad08029be.png">

**Comment by simkimsia** [comment]
love the green color passing badge! 🙌
